name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Desplegar cuando haya un push en la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Cambia la versión según tu necesidad

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Asegúrate de tener este script en tu package.json

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token=$VERCEL_TOKEN
